### PR TITLE
Support variable-height rows.

### LINKED ISSUE #43: TreeDataGrid gets stuck when a row with multiline text is added
When a row with multiline text is added, the scroll starts to slow down. Also seems like some mess happens with virtualization

TreeDataGrid-multiline

### PR DESCRIPTION
**Pull request by grokys**
Adds support for variable-height rows, and adds a Wikipedia example to the sample app to demonstrate.

Ports the virtualization algorithm from Avalonia's `VirtualizingStackPanel`.

Fixes #43

### CODE REVIEW

**Comment by SCLDGit** [comment]
Scrolling with mousewheel seems to not be so happy when trying to scroll up from the bottom of the tree

**Review by jmacato — CHANGES_REQUESTED** [review]
Scrolling up to down is quite smooth! Although going in the opposite direction is jittery as @SCLDGit said

**Comment by grokys** [comment]
`VirtualizingStackPanel` in the main Avalonia repository was based on the initial work here, but has been greatly improved. I need to take the changes to the algorithm in `VirtualizingStackPanel` and update this PR.

**Comment by grokys** [comment]
Ok, this PR should now be ready.

**Review by maxkatz6 — APPROVED** [review]

**Pull request merged**
